name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v
    
    - name: Coverage report
      id: coverage
      run: |
        go install github.com/ory/go-acc/cmd
        echo "COVERAGE=$(go-acc ./... | grep "coverage: " | awk -F"coverage: " '{sub(/ .*/,"",$2);print $2}')"
        echo "##[set-output name=coveragelines;]${COVERAGE}%"

    - name: Generate the coverage badge
      uses: emibcn/badge-action@v1
      id: badge
      with:
        label: 'Coverage'
        status: ${{ steps.coverage.outputs.coverage }}
        path: ./coverage.svg
        color: ${{ steps.coverage.outputs.coveragelines > 75 && 'green' || 'red' }}

